modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="zone_cleaner"
version="3.1.0"
displayName="Zone Cleaner"
displayURL="https://modrinth.com/project/zone-cleaner"
logoFile="logo.png"
credits="Made with MCreaHub Optimized for high-performance servers."
authors="Dreyka Oas"
description="A powerful server admin tool designed to remove blocks and entities in large areas without server lag. Includes a smart progress bar and an Undo feature."
displayTest="IGNORE_SERVER_VERSION"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.zone_cleaner]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration