modLoader="javafml"
loaderVersion="[2,)"
license="MIT License"

[[mods]]
modId="zone_cleaner"
version="3.1.0"
displayName="Zone Cleaner"
displayURL="https://modrinth.com/project/zone-cleaner"
logoFile="logo.png"
credits="Made with MCreaHub Optimized for high-performance servers."
authors="Dreyka Oas"
description="A powerful server admin tool designed to remove blocks and entities in large areas without server lag. Includes a smart progress bar and an Undo feature."
displayTest="IGNORE_SERVER_VERSION"

# Start of user code block mod configuration
# End of user code block mod configuration


# Start of user code block custom mixins
# End of user code block custom mixins

[[dependencies.zone_cleaner]]
    modId="neoforge"
    type="required"
    versionRange="[20.6.139,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.zone_cleaner]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.6]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration